theme: jekyll-theme-minimal
title: Inventor | Entrepreneur | Maker |   
description:     
logo: /assets/logo.jpg
#face: /assets/myface.jpg
show_downloads: False
google_analytics: UA-51485831-2
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Best tutorial so far https://www.taniarascia.com/make-a-static-website-with-jekyll/ 