theme: jekyll-theme-minimal
title: Maker / Inventor / Entrepreneur  
#description: Maker / Inventor / Entrepreneur  
logo: logo.jpg
show_downloads: False
face: MyFace.jpg
google_analytics: UA-51485831-2
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag